### PR TITLE
Fixes: https://github.com/MARKETProtocol/cms/issues/2

### PR DESCRIPTION
**Pull request by KClough**
##### Description

Fixes issues with blog previews rendering mark down syntax.

##### Checklist

- [x] Linter status: 100% pass
- [x] Changes don't break existing behavior
- [x] Tests coverage hasn't decreased
- [x] Issues resolved with previews
- [x] All tests updated for any new code generated / old code modified

##### Screenshots (Optional) 

screen shot 2018-08-20 at 10 03 37 pm

##### Testing

Tested by viewing the blog preview screen in latest Chrome. Ran Automated Tests

##### Refers/Fixes

Fixes: #2

### CODE REVIEW

**Comment by pelsasser** [comment]
@KClough - Visually this looks great to me, thanks for the quick turnaround!

@eswarasai - can you do a quick code review to get this merged?

**Comment by KClough** [comment]
@pelsasser Just an FYI the approach I took might not look great on Firefox as it doesn't support webkit clamp lines, which isn't currently implemented in FireFox. I didn't see any documentation covering required browser support.

**Comment by pelsasser** [comment]
@KClough - thanks for the heads up, let me take a look at it on firefox and get back to you.  Sorry there wasn't documentation regarding browser support, as part of our main site, we want to make it as broad as possible.

**Comment by KClough** [comment]
@pelsasser thats understandable, I think the current approach will render no truncation at all on Firefox, so this solution is likely incomplete for your needs. I should have some time this week to tweak the solution so it also supports all major browsers.

**Comment by pelsasser** [comment]
@KClough - its seems to look fine on firefox as of now 

image

am i missing something? lets get it merged, and we can always revisit.  Really appreciate your help here and letting us know about the limitations of the implementation!

Hope you will work on more bounties with us!

**Comment by KClough** [comment]
Nice! I'm glad it worked out. I based that around https://caniuse.com/#feat=css-line-clamp

It is possible that the react clamp component we're using is already patched to work with Firefox.

**Comment by eswarasai** [comment]
@KClough -- I'm not really sure if the issue is completely resolved here. Can you please take a look at the below screenshots and see why the Blog Preview Post doesn't render the markdown correctly?

Preview -->

screen shot 2018-08-22 at 12 03 36 am

Actual -->

screen shot 2018-08-22 at 12 03 56 am

**Comment by KClough** [comment]
@eswarasai please review the expected behavior on the issue:

```Expected Behavior
The markdown either is rendered correctly, or simply removed so we just have plain text in the preview```

In my research, I found it more reliable to simply remove the markdown in order to render the preview accurately. I tried a number of markdown to html components that would trim the rendered html, but none of them worked well.

**Comment by pelsasser** [comment]
I think this is a good solution for the previews, they dont need to be perfect, but showing the raw markdwon syntax make them look really odd.

**Comment by pelsasser** [comment]
thanks @eswarasai and @KClough paying out the bounty now!

**Pull request merged**
